
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 16 04:18:22 CST 2016
//----------------------------------------------------

package BackEnd.Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int COLUMNA = 22;
  public static final int Eliminacion = 13;
  public static final int cadena = 3;
  public static final int DESC = 23;
  public static final int Producto = 16;
  public static final int numero = 2;
  public static final int Modificar = 12;
  public static final int FILA = 21;
  public static final int ERR = 17;
  public static final int TIPO = 19;
  public static final int Direccion = 25;
  public static final int bool = 4;
  public static final int PO = 20;
  public static final int Lista = 18;
  public static final int imagen = 8;
  public static final int EOF = 0;
  public static final int Registro = 11;
  public static final int DI = 5;
  public static final int Cantidad = 30;
  public static final int Propietario = 29;
  public static final int Marca = 31;
  public static final int Telefono = 27;
  public static final int DF = 6;
  public static final int usuario = 15;
  public static final int Access = 10;
  public static final int Codigo = 28;
  public static final int Id = 24;
  public static final int error = 1;
  public static final int Reply = 9;
  public static final int Igual = 7;
  public static final int Tienda = 14;
  public static final int Sucursal = 34;
  public static final int Color = 32;
  public static final int Tamano = 33;
  public static final int Nombre = 26;
}

