
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 11 21:37:06 CST 2016
//----------------------------------------------------

package BackEnd.Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int COLUMNA = 21;
  public static final int Eliminacion = 12;
  public static final int cadena = 3;
  public static final int DESC = 22;
  public static final int Producto = 15;
  public static final int numero = 2;
  public static final int Modificar = 11;
  public static final int FILA = 20;
  public static final int ERR = 16;
  public static final int TIPO = 18;
  public static final int Direccion = 24;
  public static final int bool = 4;
  public static final int PO = 19;
  public static final int Lista = 17;
  public static final int EOF = 0;
  public static final int Registro = 10;
  public static final int DI = 5;
  public static final int Cantidad = 29;
  public static final int Propietario = 28;
  public static final int Marca = 30;
  public static final int Telefono = 26;
  public static final int DF = 6;
  public static final int usuario = 14;
  public static final int Access = 9;
  public static final int Codigo = 27;
  public static final int Id = 23;
  public static final int error = 1;
  public static final int Reply = 8;
  public static final int Igual = 7;
  public static final int Tienda = 13;
  public static final int Sucursal = 33;
  public static final int Color = 31;
  public static final int Tamano = 32;
  public static final int Nombre = 25;
}

